services:
  s1admin:
    image: dpage/pgadmin4:latest
    container_name: 68-s1-admin
    ports:
      - ${DATABASE_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_DEFAULT_PORT: ${PGADMIN_DEFAULT_PORT}
