services:
  s1app:
    image: dpage/pgadmin:latest
    container_name: 68-s1-app
    ports:
      - ${APP_DATABASE_PORT}:1337"
    environment:
      APP_DATABASE_USERNAME: ${APP_DATABASE_USERNAME}
      APP_DATABASE_PASSWORD: ${APP_DATABASE_PASSWORD}
      APP_DATABASE_CLIENT: ${APP_DATABASE_CLIENT}
      APP_DATABASE_NAME: ${APP_DATABASE_NAME}
      APP_DATABASE_HOST: ${APP_DATABASE_HOST}
      APP_DATABASE_PORT: ${APP_DATABASE_PORT}